// Paint materials as swatches for the Paint tool and the Look tab, with texture library thumbnails where they exist.
// doc.paint holds src/look MATERIALS index + 1 (0 = automatic). A MATERIALS entry with `role` is the biome's own
// material for that role (lowland, cliff…); one with `id` is a texture library material.
import { BIOMES, MATERIALS } from '../../src/look/index.js';
import { MATERIAL_LIBRARY } from '../../src/look/library-manifest.js';
import { choice, el } from './dom.js';

const LIBRARY = new Map(MATERIAL_LIBRARY.map((m) => [m.id, m]));
const CLASSES = { ground: 'Ground', slope: 'Slope', cliff: 'Cliff', shore: 'Shore', special: 'Special' };
const thumbPath = (m) => `assets/textures/${m.files.thumb}`; // generated by tools/textures; may be missing on a fresh checkout

// Thumbnails that exist, asked once at start-up so missing ones fall back to colour without 404s in the console.
let thumbs = new Set();

export async function loadThumbs() {
  const found = await window.studio.hasFiles(MATERIAL_LIBRARY.map(thumbPath));
  thumbs = new Set(MATERIAL_LIBRARY.filter((_, i) => found[i]).map((m) => m.id));
}

const css = (rgb) => `rgb(${rgb.map(Math.round).join(', ')})`;
/** A library material's look: its thumbnail over its average colour. */
const look = (id) => {
  const lib = LIBRARY.get(id);
  return { color: css(lib.avgColor), thumb: thumbs.has(id) ? `../../${thumbPath(lib)}` : null };
};

/** Swatch groups for the doc's biome: [{title, items: [{value, label, color, thumb}]}]; value is the paint id. */
function paintGroups(doc) {
  const biome = BIOMES[doc.biome], groups = [{ title: 'From the biome', items: [] }];
  const byClass = new Map(Object.keys(CLASSES).map((cls) => [cls, []]));
  MATERIALS.forEach((m, i) => {
    if (m.role) groups[0].items.push({ value: i + 1, label: m.label, ...look(biome.materials[m.role]) });
    else byClass.get(LIBRARY.get(m.id).class).push({ value: i + 1, label: m.label, ...look(m.id) });
  });
  for (const [cls, items] of byClass) if (items.length) groups.push({ title: CLASSES[cls], items });
  return groups;
}

/** A square swatch: the thumbnail over its average colour, so a missing image still shows the right colour. */
function swatch({ color, thumb }) {
  const node = el('span', { class: 'swatch square', 'aria-hidden': 'true' }, thumb ? el('img', { src: thumb, alt: '', draggable: 'false' }) : null);
  node.style.backgroundColor = color;
  return node;
}

/** A biome's ground, high ground, slope and shore looks as one gradient strip. */
export function biomeSwatch(key) {
  const b = BIOMES[key], node = el('span', { class: 'swatch', 'aria-hidden': 'true' });
  const [ground, high, slope, sand] = ['ground', 'high', 'slope', 'sand'].map((role) => look(b.materials[role]).color);
  node.style.background = `linear-gradient(90deg, ${ground} 0 30%, ${high} 30% 55%, ${slope} 55% 78%, ${sand} 78%)`;
  return node;
}

let pickers = 0;

/** The paint material picker: swatch radios grouped like the library; each names itself in a tooltip, the choice below. */
export function materialPicker(doc, current, onPick) {
  const groups = paintGroups(doc), name = `material-${++pickers}`;
  const caption = el('p', { class: 'note selected-caption' });
  const show = (v) => { caption.textContent = `Selected: ${groups.flatMap((g) => g.items).find((m) => m.value === v)?.label ?? 'none'}`; };
  const picker = el('div', { class: 'material-picker' }, ...groups.map((g) => el('div', { class: 'material-group' },
    el('h4', {}, g.title),
    el('div', { class: 'swatch-grid materials', role: 'radiogroup', 'aria-label': g.title }, ...g.items.map((m) => {
      const card = choice({ name, value: m.value, checked: m.value === current, className: 'compact', onChange: (v) => { show(Number(v)); onPick(Number(v)); } }, swatch(m));
      card.dataset.tip = m.label;
      card.querySelector('input').setAttribute('aria-label', m.label);
      return card;
    })))));
  show(current);
  return el('div', {}, picker, caption);
}
