// Paint materials as swatches for the Paint tool and the Look tab, with texture library thumbnails where they exist.
// doc.paint holds src/look MATERIALS index + 1 (0 = automatic). A MATERIALS entry without `id` is a biome role
// (lowland, cliff…: its look comes from the biome); one with `id` is a texture library material (WP 2.1 / 2.2).
import { BIOMES, MATERIALS } from '../../src/look/index.js';
import { MATERIAL_LIBRARY } from '../../src/look/library-manifest.js';
import { choice, el } from './dom.js';

const LIBRARY = new Map(MATERIAL_LIBRARY.map((m) => [m.id, m]));
const CLASSES = { ground: 'Ground', slope: 'Slope', cliff: 'Cliff', shore: 'Shore', special: 'Special' };
const thumbPath = (m) => `assets/textures/${m.files.thumb}`; // generated by tools/textures; may be missing on a fresh checkout

// Thumbnails that exist, asked once at start-up so missing ones fall back to colour without 404s in the console.
let thumbs = new Set();

export async function loadThumbs() {
  const found = await window.studio.hasFiles(MATERIAL_LIBRARY.map(thumbPath));
  thumbs = new Set(MATERIAL_LIBRARY.filter((_, i) => found[i]).map((m) => m.id));
}

const css = (rgb) => `rgb(${rgb.map(Math.round).join(', ')})`;
const swatchOf = (lib) => ({ color: css(lib.avgColor), thumb: thumbs.has(lib.id) ? `../../${thumbPath(lib)}` : null });

/** How a biome role looks: the library material the biome assigns to it, or the biome's own colour. */
function roleLook(biome, role) {
  const lib = LIBRARY.get(biome.materials?.[role]);
  return lib ? swatchOf(lib) : { color: css(biome[role]), thumb: null };
}

/**
 * Swatch groups for the doc's biome: [{title, items: [{value, label, color, thumb}]}]. value is the paint id, or null for
 * a library material the exporter cannot paint yet (MATERIALS does not list it).
 */
function paintGroups(doc) {
  const biome = BIOMES[doc.biome], groups = [{ title: 'From the biome', items: [] }];
  const paintId = new Map(MATERIALS.map((m, i) => [m.id ?? `role:${m.role ?? m.key}`, i + 1]));
  for (const m of MATERIALS) {
    if (!m.id) groups[0].items.push({ value: paintId.get(`role:${m.role ?? m.key}`), label: m.label, ...roleLook(biome, m.role ?? m.key) });
  }
  for (const [cls, title] of Object.entries(CLASSES)) {
    const items = MATERIAL_LIBRARY.filter((m) => m.class === cls).map((m) => ({ value: paintId.get(m.id) ?? null, label: m.label, ...swatchOf(m) }));
    if (items.length) groups.push({ title, items });
  }
  return groups;
}

/** A square swatch: the thumbnail over its average colour, so a missing image still shows the right colour. */
function swatch({ color, thumb }) {
  const node = el('span', { class: 'swatch square', 'aria-hidden': 'true' }, thumb ? el('img', { src: thumb, alt: '', draggable: 'false' }) : null);
  node.style.backgroundColor = color;
  return node;
}

/** A biome's ground, high ground, slope and shore looks as one gradient strip. */
export function biomeSwatch(key) {
  const b = BIOMES[key], node = el('span', { class: 'swatch', 'aria-hidden': 'true' });
  const [ground, high, slope, sand] = ['ground', 'high', 'slope', 'sand'].map((role) => roleLook(b, role).color);
  node.style.background = `linear-gradient(90deg, ${ground} 0 30%, ${high} 30% 55%, ${slope} 55% 78%, ${sand} 78%)`;
  return node;
}

let pickers = 0;

/** The paint material picker: swatch radios grouped like the library, with the chosen material's name below. */
export function materialPicker(doc, current, onPick) {
  const groups = paintGroups(doc), name = `material-${++pickers}`;
  const caption = el('p', { class: 'note' });
  const show = (v) => { caption.textContent = groups.flatMap((g) => g.items).find((m) => m.value === v)?.label ?? ''; };
  const pending = groups.some((g) => g.items.some((m) => m.value === null));
  const picker = el('div', { class: 'material-picker' }, ...groups.map((g) => el('div', { class: 'material-group' },
    el('h4', {}, g.title),
    el('div', { class: 'swatch-grid materials', role: 'radiogroup', 'aria-label': g.title }, ...g.items.map((m) => {
      const card = choice({ name, value: m.value ?? '', checked: m.value === current, disabled: m.value === null, className: m.value === null ? 'compact preview' : 'compact', onChange: (v) => { show(Number(v)); onPick(Number(v)); } }, swatch(m));
      card.dataset.tip = m.value === null ? `${m.label}: paintable once the texture export update lands` : m.label;
      card.querySelector('input').setAttribute('aria-label', m.label);
      return card;
    })))));
  show(current);
  return el('div', {}, picker, caption, pending ? el('p', { class: 'note' }, 'Library materials become paintable with the texture export update; the biome materials paint now.') : null);
}
