// Material library loading and a small PNG codec. Node-only.
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { crc32, deflateSync, inflateSync } from 'node:zlib';

// Generated by `npm run textures` (gitignored). In a git worktree, junction it to the main checkout's copy:
//   mklink /J assets\textures D:\bar_map_maker\assets\textures
// shortcut: repo-relative; the packaged app (installer, Wave 4) must pass its own resources dir as `root`.
export const TEXTURE_ROOT = resolve(import.meta.dirname, '../../assets/textures');

/**
 * A material's albedo (RGB, 3 bytes per pixel) and BAR splat detail texture (DNTS: RGBA, 4 bytes per pixel),
 * both 1024×1024, rows from the top. Layout of `dnts`: tools/textures/README.md.
 */
export function loadMaterial(id, root = TEXTURE_ROOT) {
  if (!/^[a-z0-9_]+$/.test(id)) throw new Error(`not a material id: ${id}`);
  const read = dir => decodePng(readFileSync(join(root, dir, `${id}.png`)));
  return { albedo: read('albedo'), dnts: read('dnts') };
}

const SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const CHANNELS = { 0: 1, 4: 2, 2: 3, 6: 4 }; // PNG colour type → channels (palette PNGs are not supported)
const COLOUR_TYPE = { 1: 0, 2: 4, 3: 2, 4: 6 };

/** Decodes a non-interlaced grey / grey+alpha / RGB / RGBA PNG; 16-bit samples keep their high byte. */
export function decodePng(bytes) {
  const buf = Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (!buf.subarray(0, 8).equals(SIGNATURE)) throw new Error('not a PNG');
  let width = 0, height = 0, depth = 0, channels = 0;
  const idat = [];
  for (let pos = 8; pos < buf.length;) {
    const length = buf.readUInt32BE(pos), type = buf.toString('latin1', pos + 4, pos + 8);
    const body = buf.subarray(pos + 8, pos + 8 + length);
    if (type === 'IHDR') {
      [width, height, depth, channels] = [body.readUInt32BE(0), body.readUInt32BE(4), body[8], CHANNELS[body[9]]];
      if (!channels || (depth !== 8 && depth !== 16) || body[12] !== 0) {
        throw new Error(`unsupported PNG (colour type ${body[9]}, depth ${depth}, interlace ${body[12]})`);
      }
    } else if (type === 'IDAT') idat.push(body);
    else if (type === 'IEND') break;
    pos += 12 + length;
  }
  const raw = inflateSync(Buffer.concat(idat));
  const bpp = (channels * depth) / 8, stride = width * bpp;
  if (!width || raw.length !== (stride + 1) * height) throw new Error('PNG image data has the wrong size');
  const img = new Uint8Array(stride * height);
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)], src = y * (stride + 1) + 1, row = y * stride, up = row - stride;
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? img[row + x - bpp] : 0, b = y ? img[up + x] : 0, c = x >= bpp && y ? img[up + x - bpp] : 0;
      let predictor;
      switch (filter) {
        case 0: predictor = 0; break;
        case 1: predictor = a; break;
        case 2: predictor = b; break;
        case 3: predictor = (a + b) >> 1; break;
        case 4: {
          const pa = Math.abs(b - c), pb = Math.abs(a - c), pc = Math.abs(a + b - 2 * c);
          predictor = pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
          break;
        }
        default: throw new Error(`bad PNG filter ${filter} in row ${y}`);
      }
      img[row + x] = raw[src + x] + predictor; // Uint8Array stores mod 256, as PNG wants
    }
  }
  const data = depth === 8 ? img : img.filter((_, i) => i % 2 === 0);
  return { width, height, channels, data };
}

/** Encodes 8-bit pixels (1–4 channels, inferred from the data length) as a PNG. */
export function encodePng({ width, height, data }) {
  const channels = data.length / (width * height), stride = width * channels;
  if (!(channels in COLOUR_TYPE)) throw new Error(`cannot encode ${data.length} bytes as a ${width}×${height} PNG`);
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    const dst = y * (stride + 1), row = y * stride;
    raw[dst] = 1; // "Sub" filter: each byte minus the one a pixel to its left
    for (let x = 0; x < stride; x++) raw[dst + 1 + x] = data[row + x] - (x >= channels ? data[row + x - channels] : 0);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = COLOUR_TYPE[channels];
  return Buffer.concat([SIGNATURE, chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}

function chunk(type, body) {
  const out = Buffer.alloc(12 + body.length);
  out.writeUInt32BE(body.length, 0);
  out.write(type, 4, 'latin1');
  body.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + body.length)), 8 + body.length);
  return out;
}
