// mapinfo.lua and mapconfig/lava.lua writers. Output is a plain Lua table; every user string goes through luaString.
import { biomeOf } from '../look/biomes.js';

/** A double-quoted Lua string literal; quotes, backslashes and control characters are escaped. */
function luaString(text) {
  const escape = (c) => (c === '\\' || c === '"' ? `\\${c}` : `\\${String(c.charCodeAt(0)).padStart(3, '0')}`);
  return `"${String(text).replace(/[\\"\x00-\x1f\x7f]/g, escape)}"`;
}

function luaNumber(value, name) {
  if (!Number.isFinite(value)) throw new Error(`mapinfo: ${name} must be a finite number, got ${value}`);
  return String(value);
}

const luaColor = (c) => `{ ${c.map((v) => v.toFixed(3)).join(', ')} }`;

/** File-system safe base name ('My Map' -> 'My_Map'); used for maps/<base>.smf|.smt and the archive name. */
export function mapFileBase(text) {
  const base = String(text).trim().replace(/[^\w.-]+/g, '_').replace(/^[_.]+|[_.]+$/g, '');
  if (!base) throw new Error(`"${text}" has no letters or digits to make a file name from`);
  return base;
}

function sunDirection(sunDir) {
  const [x, y, z] = sunDir ?? [];
  if (![x, y, z].every(Number.isFinite) || !(y > 0)) {
    throw new Error(`settings.sunDir must be [x, y > 0, z < 0] (sun above the horizon, in the north), got ${JSON.stringify(sunDir)}`);
  }
  // Maps opened from BAR may light from the south (Volcano King); a new export needs the northern sun the bake shades for.
  if (!(z < 0)) throw new Error(`The sun is in the south (sunDir z = ${z}); exported maps need it in the north. Move the sun to the north in the Look tab.`);
  const len = Math.hypot(x, y, z);
  return [x, y, z].map((v) => (v / len).toFixed(4)).join(', ');
}

function waterBlock(w) {
  return `
  water = {
    damage = 0.0,
    absorb = ${luaColor(w.absorb)},
    baseColor = ${luaColor(w.base)},
    minColor = ${luaColor(w.min)},
    surfaceColor = ${luaColor(w.surface)},
    planeColor = ${luaColor(w.base)},
    surfaceAlpha = 0.25,
    fresnelMin = 0.2,
    fresnelMax = 0.8,
    fresnelPower = 4.0,
    reflectionDistortion = 1.0,
    blurBase = 2.0,
    blurExponent = 1.5,
    perlinStartFreq = 8.0,
    perlinLacunarity = 3.0,
    perlinAmplitude = 0.9,
    shoreWaves = true,
  },
`;
}

/**
 * @typedef {Object} MapTextures
 * @property {Record<string, string>} resources  mapinfo resources key -> file name in the archive's maps/ folder
 * @property {{scale: number, mult: number}[]} splats  splatDetailNormalTex1..4 tiling scale and strength
 */

// resources + splats: the engine finds bare file names in the archive's maps/ folder.
function texturesBlock({ resources, splats }) {
  const files = Object.entries(resources).map(([key, file]) => `    ${key} = ${luaString(file)},`);
  const list = (name) => splats.map((s) => luaNumber(s[name], `splat ${name}`)).join(', ');
  return `  resources = {
${files.join('\n')}
    splatDetailNormalDiffuseAlpha = 1,
  },
  splats = {
    texScales = { ${list('scale')} },
    texMults = { ${list('mult')} },
  },
`;
}

/**
 * @param {import('../core/index.js').MapDoc} doc
 * @param {{fileBase: string, minHeight: number, maxHeight: number, maxMetal: number, textures: MapTextures}} extras
 *   values decided by the exporter
 * @returns {string} mapinfo.lua
 */
export function writeMapInfo(doc, { fileBase, minHeight, maxHeight, maxMetal, textures }) {
  const s = doc.settings;
  const biome = biomeOf(doc);
  const starts = doc.objects.filter((o) => o.type === 'start');
  const teams = starts.map((o, i) => `    [${i}] = { startPos = { x = ${luaNumber(Math.round(o.x), 'start x')}, z = ${luaNumber(Math.round(o.z), 'start z')} } },`);
  const needsWater = minHeight < 0 && !s.voidWater && !s.lava.enabled;
  return `-- Generated by BAR Map Studio
return {
  name = ${luaString(s.name)},
  shortname = ${luaString(fileBase)},
  description = ${luaString(s.description)},
  author = ${luaString(s.author)},
  version = ${luaString(s.version)},
  mapfile = ${luaString(`maps/${fileBase}.smf`)},
  modtype = 3,
  depend = { "Map Helper v1" },
  replace = {},

  maphardness = 100,
  notDeformable = false,
  gravity = ${luaNumber(s.gravity, 'gravity')},
  tidalStrength = ${luaNumber(s.tidalStrength, 'tidalStrength')},
  maxMetal = ${luaNumber(maxMetal, 'maxMetal')},
  extractorRadius = ${luaNumber(s.extractorRadius, 'extractorRadius')},
  voidWater = ${s.voidWater ? 'true' : 'false'},
  voidGround = false,
  autoShowMetal = true,

  smf = {
    minheight = ${luaNumber(minHeight, 'minHeight')},
    maxheight = ${luaNumber(maxHeight, 'maxHeight')},
    smtFileName0 = ${luaString(`maps/${fileBase}.smt`)},
  },

  sound = { preset = "default" },
${texturesBlock(textures)}
  atmosphere = {
    minWind = ${luaNumber(s.minWind, 'minWind')},
    maxWind = ${luaNumber(s.maxWind, 'maxWind')},
    fogStart = 0.75,
    fogEnd = 1.0,
    fogColor = ${luaColor(biome.fog)},
    skyColor = ${luaColor(biome.sky)},
    sunColor = ${luaColor(biome.sunColor)},
    cloudColor = ${luaColor(biome.fog)},
    cloudDensity = 0.4,
  },

  lighting = {
    sunDir = { ${sunDirection(s.sunDir)}, 1e9 },
    groundAmbientColor = ${luaColor(biome.ambient)},
    groundDiffuseColor = ${luaColor(biome.diffuse)},
    groundSpecularColor = { 0.1, 0.1, 0.1 },
    unitAmbientColor = ${luaColor(biome.ambient.map((v) => v * 0.9))},
    unitDiffuseColor = ${luaColor(biome.diffuse.map((v) => v * 0.95))},
    unitSpecularColor = ${luaColor(biome.diffuse.map((v) => v * 0.7))},
    specularExponent = 100.0,
    groundShadowDensity = 0.8,
    unitShadowDensity = 0.8,
  },
${needsWater ? waterBlock(biome.water) : ''}
  teams = {
${teams.join('\n')}
  },

  terrainTypes = {
    [0] = {
      name = "Default",
      hardness = 1.0,
      receiveTracks = true,
      moveSpeeds = { tank = 1.0, kbot = 1.0, hover = 1.0, ship = 1.0 },
    },
  },

  custom = { generator = "BAR Map Studio" },
}
`;
}

/**
 * BAR's map-side lava settings (read by BAR's modules/lava.lua): lava held at a fixed level all game.
 * @param {import('../core/index.js').MapDoc} doc
 * @returns {string|null} mapconfig/lava.lua, or null when the map has no lava
 */
export function writeLavaConfig(doc) {
  const { lava } = doc.settings;
  if (!lava.enabled) return null;
  const level = luaNumber(lava.level, 'lava level');
  return `-- Generated by BAR Map Studio. Units below the lava level take damage; textures are BAR's own lava set.
return {
  level = ${level},
  grow = 0,
  damage = ${luaNumber(lava.damage, 'lava damage')},
  diffuseEmitTex = "LuaUI/images/lava/lava2_diffuseemit.dds",
  normalHeightTex = "LuaUI/images/lava/lava2_normalheight.dds",
  uvScale = ${Math.max(2, Math.round(Math.max(doc.sx, doc.sz) / 2))}.0,
  coastWidth = 40.0,
  coastColor = "vec3(2.0, 0.5, 0.0)",
  coastLightBoost = 0.7,
  fogColor = "vec3(2.0, 0.5, 0.0)",
  fogFactor = 0.06,
  fogHeight = 30,
  tideAmplitude = 2,
  tidePeriod = 200,
  -- { target level, speed (elmos/s), hold time (s) }: hold the lava at its level all game
  tideRhythm = { { ${luaNumber(lava.level - 1, 'lava level')}, 1.5, 5 * 6000 } },
}
`;
}
